TWITTER_CONSUMER_KEY: 'GVGT0JlUb4acCF8cHtw6A'
TWITTER_CONSUMER_SECRET: 'PmHdEX9J6Bs1X0SwIzaA6CrgJzLNvfTkfR1Okzz1tE'

BITLY_LOGIN: "pkinnaiibm"
BITLY_API_KEY: "R_df846563a096abc1e6d992aa9710ce8d"

AMAZON_ACCESS_KEY: 'AKIAJXWVOI5P2VJJHKVQ'
AMAZON_SECRET_KEY: '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'